---
title: "Stopwords"
author: "Soledad Araya"
date: "2026-04-02"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# General
library(tidyverse)

# texto
library(quanteda)
library(quanteda.textstats)
library(tidytext)
library(readtext)
library(stringi)

# ggplot
library(hrbrthemes)
```

# Carga de documentos

```{r}
# Dirección por país
paths <- list.files("data_raw/interviews/argentina", pattern = "\\.docx$", full.names = TRUE)

docs_argentina <- readtext(paths)

docs_argentina <- docs_argentina |> 
  mutate(text = stri_trans_general(text, "latin-ascii"),
         text = str_remove_all(text, "[[:punct:]]"),
         text = str_to_lower(text),
         text = str_squish(text))

head(docs_argentina$text, 2)  # muestra del primer texto

docs_argentina <- docs_argentina |> 
  mutate(pais = "Argentina")
```

# España

```{r}
# Dirección por país
paths <- list.files("data_raw/interviews/españa", pattern = "\\.docx$", full.names = TRUE)

docs_espana <- readtext(paths)

docs_espana <- docs_espana |> 
  mutate(text = stri_trans_general(text, "latin-ascii"),
         text = str_remove_all(text, "[[:punct:]]"),
         text = str_to_lower(text),
         text = str_squish(text))

head(docs_espana$text, 2)  # muestra del primer texto

docs_espana <- docs_espana |> 
  mutate(pais = "España")
```

# Unir en una sola base

```{r}
docs <- bind_rows(docs_argentina,
                  docs_espana)

rm(docs_argentina, docs_espana, paths)
```


### Integrar Clasificacion.xlsx

```{r}
entrevistas <- readxl::read_xlsx("input/Clasificacion.xlsx") |> 
  janitor::clean_names()

colnames(entrevistas)

entrevistas <- entrevistas |> 
  mutate(across(rama_feminista:autonomia_que_expande, ~str_to_title(.)),
         entrevista_id = paste(entrevistas, pais))
```

Identificador de entrevista sin extensión

```{r}
docs$doc_id <- tools::file_path_sans_ext(basename(docs$doc_id))
```

```{r}
docs <- docs |> 
  mutate(doc_id = str_to_title(doc_id),
         doc_id = paste(doc_id, pais)) |> 
  select(-pais)
```

Unir las bases

```{r}
docs <- docs |> 
  left_join(entrevistas, by = c("doc_id"="entrevista_id"))

colnames(docs)

docs <- docs |> 
  mutate(doc_id = paste("Entrevista", 1:n())) |> 
  select(doc_id, pais, rama_feminista, tipo_de_femocrata, nivel_territorial, 
         autonomia_que_expande, texto = text)
```

# Corpus

```{r}
corp <- quanteda::corpus(docs, text_field = "texto")
```

# Estandarización

```{r}
toks <- tokens(corp,
               remove_punct   = TRUE,
               remove_numbers = TRUE,
               remove_symbols = TRUE)

# Quitar términos de dos o menos letras

toks <- tokens_keep(toks, pattern = "^[[:alpha:]]{3,}$", valuetype = "regex")
```

Diccionario propio de palabras para eliminar:

```{r}
stop_es <- tibble(word = stopwords("es"))

stop_es <- stop_es |>
  mutate(
    word = stri_trans_general(word, "latin-ascii"),
    word = str_remove_all(word, "[[:punct:]]"),
    word = str_to_lower(word)
  )
```


```{r}

revision_palabras <- docs |> 
  unnest_tokens(word, texto)  |> 
  count(word)

revision_palabras <- revision_palabras |> 
  filter(!str_detect(word, "\\d")) |> # Eliminar números
  filter(nchar(word) > 3) # Eliminar palabras 2 o menos letras

revision_palabras_limpia <- revision_palabras  |> 
  anti_join(stop_es, by = "word")

revision_palabras_limpia <- revision_palabras_limpia |> 
  filter(n > 10)

# Revisar luego de guardar

writexl::write_xlsx(revision_palabras_limpia, "outputs/palabras.xlsx")

rm(revision_palabras, revision_palabras_limpia)
```

```{r}

palabras <- readxl::read_xlsx("input/diccionario.xlsx")
  
dic_propio <- palabras |> 
  filter(is.na(eliminar)) |> 
  select(word) |> 
  pull()

```

Eliminar stopwords del corpus

```{r}
# Remover stopwords

stop_all <- unique(c(stop_es, dic_propio))

toks <- tokens_remove(toks, stop_all)
```


Dejar sólo palabras con un mínimo de 2 repeticiones

```{r}
dfm_docs <- dfm(toks)

dfm_docs <- dfm_trim(dfm_docs, min_termfreq = 3)  
```


```{r}
dfm_grouped <- dfm_group(dfm_docs, groups = tipo_de_femocrata)

topfeatures(dfm_grouped, 50)
```


# Guardamos la base de datos

```{r}
write_rds(dfm_docs, "outputs/260409-data_dfm.rds")
```


