---
title: "Revisión corpus"
author: "Soledad Araya"
date: "2026-04-02"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
```

```{r}
# General
library(tidyverse)

# texto
library(quanteda)
library(quanteda.textstats)
library(quanteda.textplots)
library(tidytext)
library(readtext)
library(stringi)

# ggplot
library(hrbrthemes)
```

# Carga de documentos

```{r}
dfm_docs <- read_rds("outputs/260422-data_dfm.rds")
```

# Exploración de base de datos

## Comparación entre grupos de referencia

```{r}

dfm_filtrado <- dfm_subset(dfm_docs, !is.na(tipo_de_femocrata))

docvars(dfm_docs)

key <- textstat_keyness(dfm_filtrado, target = docvars(dfm_filtrado)$tipo_de_femocrata == "Estado")

key |> 
  mutate(feature = str_to_upper(gsub("_", " ", feature)),
         grupo = ifelse(chi2 > 0, "Estado", "Referencia"))  |> 
  group_by(grupo) |> 
  slice_max(order_by = abs(chi2), n = 10, with_ties = FALSE)  |> 
  ungroup() |> 
  filter(!is.na(grupo)) |> 
  ggplot(aes(x = chi2, y = reorder(feature, chi2), fill = grupo)) +
  geom_col() +
  scale_fill_manual(values = c("#669bbc","#c1121f")) +
  labs(
    title = "Palabras características del discurso de femócrata de Estado vs de referencia.",
    subtitle = "Argentina, España y Chile.",
    x = "Keyness (log-likelihood)",
    y = NULL,
    caption = "N = 30\nElaboración propia utilizando como fuente entrevistas en profundidad.",
    fill = "Grupo"
  ) +
  theme_minimal(base_family = "Roboto") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```


```{r}

dfm_filtrado <- dfm_subset(dfm_docs, !is.na(rama_feminista) & pais=="Argentina")

docvars(dfm_docs)

key <- textstat_keyness(dfm_filtrado, target = docvars(dfm_filtrado)$rama_feminista == "Militante")


key |> 
  mutate(feature = str_to_upper(gsub("_", " ", feature)),
         grupo = ifelse(chi2 > 0, "Militante", "Referencia"))  |> 
  group_by(grupo) |> 
  slice_max(order_by = abs(chi2), n = 10, with_ties = FALSE)  |> 
  ungroup() |> 
  filter(!is.na(grupo)) |> 
  ggplot(aes(x = chi2, y = reorder(feature, chi2), fill = grupo)) +
  geom_col() +
  scale_fill_manual(values = c("#669bbc","#c1121f")) +
  labs(
    title = "ARGENTINA",
    x = "Keyness (log-likelihood)",
    y = NULL,
    fill = "Grupo"
  ) +
  theme_minimal(base_family = "Roboto") +
  theme(plot.title = element_text(hjust = 0.5))





dfm_filtrado <- dfm_subset(dfm_docs, !is.na(rama_feminista) & pais=="España")

docvars(dfm_docs)

key <- textstat_keyness(dfm_filtrado, target = docvars(dfm_filtrado)$rama_feminista == "Militante")

key |> 
  mutate(feature = str_to_upper(gsub("_", " ", feature)),
         grupo = ifelse(chi2 > 0, "Militante", "Referencia"))  |> 
  group_by(grupo) |> 
  slice_max(order_by = abs(chi2), n = 10, with_ties = FALSE)  |> 
  ungroup() |> 
  filter(!is.na(grupo)) |> 
  ggplot(aes(x = chi2, y = reorder(feature, chi2), fill = grupo)) +
  geom_col() +
  scale_fill_manual(values = c("#669bbc","#c1121f")) +
  labs(
    title = "ESPAÑA",
    x = "Keyness (log-likelihood)",
    y = NULL,
    fill = "Grupo"
  ) +
  theme_minimal(base_family = "Roboto") +
  theme(plot.title = element_text(hjust = 0.5))


key  |> 
  mutate(feature = str_to_upper(gsub("_", " ", feature)),
         grupo = ifelse(chi2 > 0, "Militante", "Referencia")) |> 
  group_by(grupo)  |> 
  slice_max(frecuencia, n = 10, with_ties = FALSE)  |> 
  ungroup()  |> 
  ggplot(aes(x = doc_id, y = reorder(palabra, frecuencia), fill = frecuencia)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "steelblue") +
  labs(x = NULL, y = NULL, fill = "Frecuencia") +
  theme_minimal()

```



# Revisión temática de acuerdo a diccionario

```{r}
dfm_dict  <- quanteda::dfm_lookup(dfm_docs, dictionary = dict_fem)

doc_theme <- quanteda::convert(dfm_dict, to = "data.frame")
```

