---
title: "Gráficos"
author: "Soledad Araya"
date: "2026-04-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
```

Paquetes

```{r}
# General
library(tidyverse)

# texto
library(quanteda)
library(quanteda.textstats)
library(tidytext)
library(readtext)
library(stringi)

# ggplot
library(hrbrthemes)

# Tipic modelling
library(topicmodels)

```

# Carga de documentos

```{r}
dfm_docs <- read_rds("outputs/260422-data_dfm.rds")
```


```{r}
modelo <- LDA(dfm_docs,
              k = 2,
              control = list(seed = 0904))
```

```{r}
temas <- tidy(modelo, 
              matrix = "beta")
```

Graficamos:

```{r}
gg_temas <- temas  |> 
  group_by(topic)  |> 
  slice_max(beta, n = 10)  |>  
  ungroup()  |> 
  arrange(topic, -beta)

# Palabras más comunas por cada tema

gg_temas  |>
  mutate(term = reorder_within(term, beta, topic)) |>
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered() +
  theme_ipsum()
```

Términos más diferentes entre las temáticas

```{r}
beta_wide <- temas  |> 
  mutate(topic = paste0("topic", topic)) |> 
  pivot_wider(names_from = topic, values_from = beta) |> 
  filter(topic1 > .001 | topic2 > .001) |> 
  mutate(log_ratio = log2(topic2 / topic1))

gg_beta_wide <- beta_wide  |> 
  slice_max(log_ratio, n = 20)  |>  
  ungroup()  |> 
  arrange(topic, -beta)

beta_wide |> 
  filter()
  ggplot(aes(x = term,))

```

# Paquete stm

```{r}
library(stm)
```

Cambiamos el formato del diccionario

```{r}
dfm_stm <- convert(dfm_docs, to = "stm")
```

Evaluamos los modelos:

```{r}
model <- stm(documents = dfm_stm$documents,
         vocab = dfm_stm$vocab, 
         K = 5,
         verbose = TRUE)

plot(model)

labelTopics(model,topics = c(1:3), n=5)
```

FREX: qué palabras son más comunes (en términos comparados) y exclusivas para esa temática.

```{r}
labels <- labelTopics(model, n = 20)
```

# Dejamos sólo FREX

```{r}
topwords <- data.frame("features" = t(labels$frex))

colnames(topwords) <- paste("topics", c(1:5))

topwords[1:5]
```


