---
title: "06-diccionarios_tematicos"
author: "Soledad Araya"
date: "2026-04-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
```

```{r}
# General
library(tidyverse)

# texto
library(quanteda)
library(quanteda.textstats)
library(tidytext)
library(readtext)
library(stringi)

# ggplot
library(hrbrthemes)
```

Cargar base de datos

```{r}
df_diccionarios_tematicos <- readxl::read_xlsx("input/260427-diccionario.xlsx")
```

```{r}
toks <- read_rds("outputs/260429-toks.rds")
```


```{r}

# Diccionario: defensa
dict_defensa <- df_diccionarios_tematicos  |> 
  filter(defensa == 1) |> 
  pull(tokens)

# Diccionario: antigénero
dict_antigenero <- df_diccionarios_tematicos |> 
  filter(antigenero == 1)  |> 
  pull(tokens)

# Diccionario: brechas
dict_brechas <- df_diccionarios_tematicos |> 
  filter(brechas == 1) |> 
  pull(tokens)
```


```{r}
diccionario <- dictionary(list(
  defensa = dict_defensa,
  antigenero = dict_antigenero,
  brechas = dict_brechas
))
```

```{r}
dfm_dic <- dfm(toks)  |> 
  dfm_lookup(diccionario)

docvars(dfm_dic)
```

```{r}
dfm_prop <- dfm_weight(dfm_dic, scheme = "prop")
```
 

# Marcos discursivos

### Nivel territorial

```{r}
df_plot_nivel <- dfm_dic |>
  convert(to = "data.frame") |>
  bind_cols(docvars(toks)) |>
  group_by(pais, nivel_territorial) |>
  summarise(across(defensa:brechas, mean, na.rm = TRUE)) |>
  pivot_longer(defensa:brechas,
               names_to = "dimension",
               values_to = "valor")

df_plot_nivel |> 
  print(n = 20)
```

```{r}
ggplot(df_plot_nivel, aes(x = pais, y = valor, fill = dimension)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(valor)),
            position = position_dodge(width = 1), vjust = -1, hjust = 0.5,
            size = 3) +
  facet_wrap(~nivel_territorial) +
  scale_fill_manual(values = c("#e76f51", "#e9c46a", "#2a9d8f"),
                    labels = c("Discurso antigénero", "Brechas de género", "Defensa de derechos")) +
  scale_y_continuous(limits = c(0,100),) +
  labs(
    title = NULL,
    x = "País",
    y = "Frecuencia promedio (proporcional)",
    fill = "Dimensión"
  ) +
  theme_minimal(base_family = "Roboto")
```

```{r}
df_plot_nivel |>
  mutate(
    dimension = case_match(
      dimension,
      "defensa" ~ "Defensa de\nderechos",
      "antigenero" ~ "Discurso\nantigénero",
      "brechas" ~ "Brechas de\ngénero"
    )
  ) |>
  ggplot(aes(x = dimension, y = pais, fill = valor)) +
  geom_tile() +
  facet_wrap( ~ nivel_territorial) +
  scale_fill_gradient2(
    low = "#ecf39e",
    # Palabra menos característica de este grupo
    mid = "#4f772d",
    # Promedio
    high = "#132a13",
    # Palabra más característica de ese grupo
    midpoint = 10,
    name = "Representación\n"
  ) +
  labs(title = NULL,
       x = "Dimensión",
       y = "País",
       fill = "Intensidad") +
  theme_minimal(base_family = "Roboto")
```

### Rama feminista

```{r}
df_plot_disc_rama <- dfm_dic |>
  convert(to = "data.frame") |>
  bind_cols(docvars(corp)) |>
  group_by(pais, rama_feminista) |>
  summarise(across(defensa:brechas, mean, na.rm = TRUE)) |>
  pivot_longer(defensa:brechas,
               names_to = "dimension",
               values_to = "valor")
```

```{r}
ggplot(df_plot_disc_rama, aes(x = pais, y = valor, fill = dimension)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(valor, )),
            position = position_dodge(width = 1), vjust = -1,
            size = 3) +
  facet_wrap(~rama_feminista) +
  scale_fill_manual(values = c("#e76f51", "#e9c46a", "#2a9d8f"),
                    labels = c("Discurso antigénero", "Brechas de género", "Defensa de derechos")) +
  scale_y_continuous(limits = c(0,100),) +
  labs(
    title = "Intensidad de marcos discursivos por país y nivel territorial",
    x = "País",
    y = "Frecuencia promedio (proporcional)",
    fill = "Dimensión"
  ) +
  theme_minimal(base_family = "Roboto")
```


```{r}
df_plot_disc_rama |>
  mutate(
    dimension = case_match(
      dimension,
      "defensa" ~ "Defensa de\nderechos",
      "antigenero" ~ "Discurso\nantigénero",
      "brechas" ~ "Brechas de\ngénero"
    )
  ) |>
  ggplot(aes(x = dimension, y = pais, fill = valor)) +
  geom_tile() +
  facet_wrap( ~ rama_feminista) +
  scale_fill_gradient2(
    low = "#ecf39e",
    # Palabra menos característica de este grupo
    mid = "#4f772d",
    # Promedio
    high = "#132a13",
    # Palabra más característica de ese grupo
    midpoint = 10,
    name = "Representación\n"
  ) +
  labs(title = NULL,
       x = "Dimensión",
       y = "País",
       fill = "Intensidad") +
  theme_minimal(base_family = "Roboto")
```




### Tipo de femocrata


 
```{r}
df_plot_disc_fem <- dfm_dic |>
  convert(to = "data.frame") |>
  bind_cols(docvars(corp)) |>
  group_by(pais, tipo_de_femocrata) |>
  summarise(across(defensa:brechas, mean, na.rm = TRUE)) |>
  pivot_longer(defensa:brechas,
               names_to = "dimension",
               values_to = "valor")
```

```{r}
ggplot(df_plot_disc_fem, aes(x = pais, y = valor, fill = dimension)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(valor)),
            position = position_dodge(width = 1), vjust = -1,
            size = 3) +
  facet_wrap(~tipo_de_femocrata) +
  scale_fill_manual(values = c("#e76f51", "#e9c46a", "#2a9d8f"),
                    labels = c("Discurso antigénero", "Brechas de género", "Defensa de derechos")) +
  scale_y_continuous(limits = c(0,100),) +
  labs(
    title = "Intensidad de marcos discursivos por país y nivel territorial",
    x = "País",
    y = "Frecuencia promedio (proporcional)",
    fill = "Dimensión"
  ) +
  theme_minimal(base_family = "Roboto")
```


```{r}
df_plot_disc_fem |>
  mutate(
    dimension = case_match(
      dimension,
      "defensa" ~ "Defensa de\nderechos",
      "antigenero" ~ "Discurso\nantigénero",
      "brechas" ~ "Brechas de\ngénero"
    )
  ) |>
  ggplot(aes(x = dimension, y = pais, fill = valor)) +
  geom_tile() +
  facet_wrap( ~ tipo_de_femocrata) +
  scale_fill_gradient2(
    low = "#ecf39e",
    # Palabra menos característica de este grupo
    mid = "#4f772d",
    # Promedio
    high = "#132a13",
    # Palabra más característica de ese grupo
    midpoint = 10,
    name = "Representación\n"
  ) +
  labs(title = NULL,
       x = "Dimensión",
       y = "País",
       fill = "Intensidad") +
  theme_minimal(base_family = "Roboto")
```




### Autonomía que expande


 
```{r}
df_plot_disc_aut <- dfm_dic |>
  convert(to = "data.frame") |>
  bind_cols(docvars(corp)) |>
  group_by(pais, autonomia_que_expande) |>
  summarise(across(defensa:brechas, mean, na.rm = TRUE)) |>
  pivot_longer(defensa:brechas,
               names_to = "dimension",
               values_to = "valor")
```

```{r}
ggplot(df_plot_disc_aut, aes(x = pais, y = valor, fill = dimension)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(valor)),
            position = position_dodge(width = 1), vjust = -1,
            size = 3) +
  facet_wrap(~autonomia_que_expande) +
  scale_fill_manual(values = c("#e76f51", "#e9c46a", "#2a9d8f"),
                    labels = c("Discurso antigénero", "Brechas de género", "Defensa de derechos")) +
  scale_y_continuous(limits = c(0,100),) +
  labs(
    title = NULL,
    x = "País",
    y = "Frecuencia promedio (proporcional)",
    fill = "Dimensión"
  ) +
  theme_minimal(base_family = "Roboto")
```


```{r}
df_plot_disc_aut |>
  mutate(
    dimension = case_match(
      dimension,
      "defensa" ~ "Defensa de\nderechos",
      "antigenero" ~ "Discurso\nantigénero",
      "brechas" ~ "Brechas de\ngénero"
    )
  ) |>
  ggplot(aes(x = dimension, y = pais, fill = valor)) +
  geom_tile() +
  facet_wrap( ~ autonomia_que_expande) +
  scale_fill_gradient2(
    low = "#ecf39e",
    # Palabra menos característica de este grupo
    mid = "#4f772d",
    # Promedio
    high = "#132a13",
    # Palabra más característica de ese grupo
    midpoint = 10,
    name = "Representación\n"
  ) +
  labs(title = NULL,
       x = "Dimensión",
       y = "País",
       fill = "Intensidad") +
  theme_minimal(base_family = "Roboto")
```






# Diccionario Temas Vinculos

```{r}

# Diccionario: defensa
dict_ong <- df_diccionarios_tematicos  |> 
  filter(ong == 1) |> 
  pull(tokens)

# Diccionario: antigénero
dict_mov_feminista <- df_diccionarios_tematicos |> 
  filter(mov_feminista == 1)  |> 
  pull(tokens)

# Diccionario: brechas
dict_partidos <- df_diccionarios_tematicos |> 
  filter(partidos == 1)  |> 
  pull(tokens)
```


```{r}
diccionario_vinculos <- dictionary(list(
  ong = dict_ong,
  mov_feminista = dict_mov_feminista,
  partidos = dict_partidos
))
```


```{r}
dfm_dic_vinculos <- dfm(toks)  |> 
  dfm_lookup(diccionario_vinculos)

docvars(dfm_dic_vinculos)
```

```{r}
dfm_prop_vinc <- dfm_weight(dfm_dic_vinculos, scheme = "prop")
```


### Nivel territorial


```{r}

df_plot_vinc <- dfm_dic_vinculos |>
  convert(to = "data.frame") |>
  bind_cols(docvars(corp)) |>
  group_by(pais, nivel_territorial) |>
  summarise(across(ong:partidos, mean, na.rm = TRUE)) |>
  pivot_longer(ong:partidos,
               names_to = "dimension",
               values_to = "valor")
```

```{r}
ggplot(df_plot_vinc, aes(x = pais, y = valor, fill = dimension)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(valor)),
            position = position_dodge(width = 1), vjust = -1,
            size = 3) +
  facet_wrap(~nivel_territorial) +
  scale_fill_manual(values = c("#e76f51", "#e9c46a", "#2a9d8f"),
                    labels = c("Movimiento feminista", "ONG", "Partidos políticos")) +
  scale_y_continuous(limits = c(0,100),) +
  labs(
    title = NULL,
    x = "País",
    y = "Frecuencia promedio (proporcional)",
    fill = "Dimensión"
  ) +
  theme_minimal(base_family = "Roboto")
```



```{r}
df_plot_vinc |>
  mutate(
    dimension = case_match(
      dimension,
      "ong" ~ "ONG",
      "mov_feminista" ~ "Movimiento\nfeminista",
      "partidos" ~ "Partidos\npolíticos"
    )
  ) |>
  ggplot(aes(x = dimension, y = pais, fill = valor)) +
  geom_tile() +
  facet_wrap( ~ nivel_territorial) +
  scale_fill_gradient2(
    low = "#ecf39e",
    # Palabra menos característica de este grupo
    mid = "#4f772d",
    # Promedio
    high = "#132a13",
    # Palabra más característica de ese grupo
    midpoint = 10,
    name = "Representación\n"
  ) +
  labs(title = NULL,
       x = "Dimensión",
       y = "País",
       fill = "Intensidad") +
  theme_minimal(base_family = "Roboto")
```

Modelo

```{r}
df_doc <- dfm_dic_vinculos |>
  convert(to = "data.frame") |>
  bind_cols(docvars(corp))

lm_mov <- lm(mov_feminista ~ pais * nivel_territorial, data = df_doc)

summary(lm_mov)

lm_ong <- lm(ong ~ pais * nivel_territorial, data = df_doc)

summary(lm_ong)

lm_partidos <- lm(partidos ~ pais * nivel_territorial, data = df_doc)

summary(lm_partidos)
```



### Rama feminista


```{r}

df_plot_vinc_rama <- dfm_dic_vinculos |>
  convert(to = "data.frame") |>
  bind_cols(docvars(corp)) |>
  group_by(pais, rama_feminista) |>
  summarise(across(ong:partidos, mean, na.rm = TRUE)) |>
  pivot_longer(ong:partidos,
               names_to = "dimension",
               values_to = "valor")
```

```{r}
ggplot(df_plot_vinc_rama, aes(x = pais, y = valor, fill = dimension)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(valor)),
            position = position_dodge(width = 1), vjust = -1,
            size = 3) +
  facet_wrap(~rama_feminista) +
  scale_fill_manual(values = c("#e76f51", "#e9c46a", "#2a9d8f"),
                    labels = c("Movimiento feminista", "ONG", "Partidos políticos")) +
  scale_y_continuous(limits = c(0,100),) +
  labs(
    title = NULL,
    x = "País",
    y = "Frecuencia promedio (proporcional)",
    fill = "Dimensión"
  ) +
  theme_minimal(base_family = "Roboto")
```



```{r}
df_plot_vinc_rama |>
  mutate(
    dimension = case_match(
      dimension,
      "ong" ~ "ONG",
      "mov_feminista" ~ "Movimiento\nfeminista",
      "partidos" ~ "Partidos\npolíticos"
    )
  ) |>
  ggplot(aes(x = dimension, y = pais, fill = valor)) +
  geom_tile() +
  facet_wrap( ~ rama_feminista) +
  scale_fill_gradient2(
    low = "#ecf39e",
    # Palabra menos característica de este grupo
    mid = "#4f772d",
    # Promedio
    high = "#132a13",
    # Palabra más característica de ese grupo
    midpoint = 10,
    name = "Representación\n"
  ) +
  labs(title = NULL,
       x = "Dimensión",
       y = "País",
       fill = "Intensidad") +
  theme_minimal(base_family = "Roboto")
```




### Tipo de femocrata



```{r}

df_plot_vinc_tipo <- dfm_dic_vinculos |>
  convert(to = "data.frame") |>
  bind_cols(docvars(corp)) |>
  group_by(pais, tipo_de_femocrata) |>
  summarise(across(ong:partidos, mean, na.rm = TRUE)) |>
  pivot_longer(ong:partidos,
               names_to = "dimension",
               values_to = "valor")
```

```{r}
ggplot(df_plot_vinc_tipo, aes(x = pais, y = valor, fill = dimension)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(valor)),
            position = position_dodge(width = 1), vjust = -1,
            size = 3) +
  facet_wrap(~tipo_de_femocrata) +
  scale_fill_manual(values = c("#e76f51", "#e9c46a", "#2a9d8f"),
                    labels = c("Movimiento feminista", "ONG", "Partidos políticos")) +
  scale_y_continuous(limits = c(0,100),) +
  labs(
    title = NULL,
    x = "País",
    y = "Frecuencia promedio (proporcional)",
    fill = "Dimensión"
  ) +
  theme_minimal(base_family = "Roboto")
```



```{r}
df_plot_vinc_tipo |>
  mutate(
    dimension = case_match(
      dimension,
      "ong" ~ "ONG",
      "mov_feminista" ~ "Movimiento\nfeminista",
      "partidos" ~ "Partidos\npolíticos"
    )
  ) |>
  ggplot(aes(x = dimension, y = pais, fill = valor)) +
  geom_tile() +
  facet_wrap( ~ tipo_de_femocrata) +
  scale_fill_gradient2(
    low = "#ecf39e",
    # Palabra menos característica de este grupo
    mid = "#4f772d",
    # Promedio
    high = "#132a13",
    # Palabra más característica de ese grupo
    midpoint = 10,
    name = "Representación\n"
  ) +
  labs(title = NULL,
       x = "Dimensión",
       y = "País",
       fill = "Intensidad") +
  theme_minimal(base_family = "Roboto")

```


### Autonomía que expande


```{r}

df_plot_vinc_autonomia <- dfm_dic_vinculos |>
  convert(to = "data.frame") |>
  bind_cols(docvars(corp)) |>
  group_by(pais, autonomia_que_expande) |>
  summarise(across(ong:partidos, mean, na.rm = TRUE)) |>
  pivot_longer(ong:partidos,
               names_to = "dimension",
               values_to = "valor")
```

```{r}
ggplot(df_plot_vinc_autonomia, aes(x = pais, y = valor, fill = dimension)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = round(valor)),
            position = position_dodge(width = 1), vjust = -1,
            size = 3) +
  facet_wrap(~autonomia_que_expande) +
  scale_fill_manual(values = c("#e76f51", "#e9c46a", "#2a9d8f"),
                    labels = c("Movimiento feminista", "ONG", "Partidos políticos")) +
  scale_y_continuous(limits = c(0,100),) +
  labs(
    title = NULL,
    x = "País",
    y = "Frecuencia promedio (proporcional)",
    fill = "Dimensión"
  ) +
  theme_minimal(base_family = "Roboto")
```




```{r}
df_plot_vinc_autonomia |>
  mutate(
    dimension = case_match(
      dimension,
      "ong" ~ "ONG",
      "mov_feminista" ~ "Movimiento\nfeminista",
      "partidos" ~ "Partidos\npolíticos"
    )
  ) |>
  ggplot(aes(x = dimension, y = pais, fill = valor)) +
  geom_tile() +
  facet_wrap( ~ autonomia_que_expande) +
  scale_fill_gradient2(
    low = "#ecf39e",
    # Palabra menos característica de este grupo
    mid = "#4f772d",
    # Promedio
    high = "#132a13",
    # Palabra más característica de ese grupo
    midpoint = 10,
    name = "Representación\n"
  ) +
  labs(title = NULL,
       x = "Dimensión",
       y = "País",
       fill = "Intensidad") +
  theme_minimal(base_family = "Roboto")
```


